In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score

import numpy as np

# suppress warnings
import warnings
warnings.filterwarnings('ignore')
#warnings.filterwarnings(action='once')

In [17]:
iris = load_iris()

## Logistic Regression

In [18]:
scores = cross_val_score(LogisticRegression(), iris.data, iris.target)
scores

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [19]:
np.average(scores)

0.9733333333333334

## Decision Tree

In [20]:
scores = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target)
scores

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [21]:
np.average(scores)

0.9600000000000002

## Support Vector Machine (SVM)

In [22]:
scores = cross_val_score(SVC(), iris.data, iris.target)
scores

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [23]:
np.average(scores)

0.9666666666666666

## Random Forest

In [24]:
scores = cross_val_score(RandomForestClassifier(n_estimators=40), iris.data, iris.target)
scores

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [25]:
np.average(scores)

0.9666666666666668