In [19]:
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt

# suppress warnings
import warnings
warnings.filterwarnings('ignore')
#warnings.filterwarnings(action='once')

In [20]:
digits = load_digits()

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

# Logistic Regression

In [22]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9722222222222222

# SVM

In [23]:
from sklearn.svm import SVC

svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.3888888888888889

# Random Forest

In [24]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9814814814814815

# KFold cross validation

### Basic example

In [25]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [26]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


### Use KFold for our digits example

In [27]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [28]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))

In [29]:
scores_logistic

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [30]:
scores_rf

[0.9315525876460768, 0.9482470784641068, 0.9232053422370617]

In [31]:
scores_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

### With Tune parameter

In [32]:
scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))

In [33]:
scores_logistic

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [34]:
scores_rf

[0.9332220367278798, 0.9632721202003339, 0.9315525876460768]

In [18]:
scores_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

## cross_val_score function

cross_val_score uses stratifield kfold by default

In [35]:
from sklearn.model_selection import cross_val_score

### Logistic regression model performance using cross_val_score

In [36]:
cross_val_score(LogisticRegression(), digits.data, digits.target)

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

### svm model performance using cross_val_score

In [37]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

### random forest performance using cross_val_score

In [39]:
cross_val_score(RandomForestClassifier(), digits.data, digits.target)

array([0.925     , 0.91388889, 0.95543175, 0.96100279, 0.93036212])

## Parameter tunning using k fold cross validation

In [43]:
scores = cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=10)
np.average(scores)

0.9259745499689634

In [48]:
scores = cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=10)
np.average(scores)

0.48198324022346367

In [45]:
scores = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores)

0.8631253879577901

In [46]:
scores = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(scores)

0.9348789571694599

In [47]:
scores = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
np.average(scores)

0.9437833643699565

In [49]:
scores = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(scores)

0.946582867783985

Here we used cross_val_score to fine tune our random forest classifier and figured that having around 40 trees in random forest gives best result.