In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [30]:
df = pd.read_csv("datasets\homeprices_multiple_dependent_variable.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

# Data Preprocessing: Fill NA values with median value of a column

In [32]:
import math
bedrooms_mean = math.floor(df.bedrooms.mean())
bedrooms_mean

4

In [33]:
df.bedrooms.fillna(bedrooms_mean, inplace=True)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [34]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

# price = m1 * area + m2 * bedrooms + m3 * age + c

In [35]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [36]:
reg.intercept_

221323.00186540443

# Find price of home with 3000 sqr ft area, 4 bedrooms, 15 year old

In [37]:
reg.predict([[3000,4,15]])

array([602590.07937407])

In [38]:
112.06244194*3000 + 23388.88007794*4 + -3231.71790863*15 + 221323.00186540384

602590.0793677138

# Find price of home with 2500 sqr ft area, 4 bedrooms, 5 year old

In [39]:
reg.predict([[2500, 4, 5]])

array([578876.03748933])